# Generated by Django 5.2 on 2025-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_menuitem_image_url_menuitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
